import Head from 'next/head'
import { useContext } from 'react'

import Button from '../components/Button'
import TodoList from '../components/TodoList'

import { TodoContext } from '@/context/TodoContext'

const Home = () => {
  const {isUserLoggedIn} = useContext(TodoContext)

  return (
    <>
      <Head>
        <title>Todo List DApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='bg-[#192542] h-screen w-screen flex justify-center py-6'>
      {!isUserLoggedIn ? <Button /> : <TodoList /> }
    </div>
    </>
  )
}

export default Home;





