import Head from 'next/head'
import { useContext } from 'react'

import ConnectWalletButton from '../components/ConnectWalletButton'
import TodoList from '../components/TodoList'

import { TodoContext } from '@/context/TodoContext'


export default function Home() {
  const {isUserLoggedIn} = useContext(TodoContext)

  return (
    <>
      <Head>
        <title>Todo DApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='bg-[#192542] h-screen w-screen flex justify-center py-6'>
      {!isUserLoggedIn ? <ConnectWalletButton /> : <TodoList /> }
    </div>
    </>
  )
}


/*

/* 
const tasks = [
  { id: 0, taskText: 'clean', isDeleted: false }, 
  { id: 1, taskText: 'food', isDeleted: false }, 
  { id: 2, taskText: 'water', isDeleted: true }
]
*/




